apiVersion: v1
kind: ConfigMap
metadata:
  name: hirevoice-backend-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "hirevoice.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backendConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
