apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: {{ .Values.hirevoiceNamespace | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.rdsSecretName | quote }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.rdsSecretName | quote }}
        property: password
