apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: {{ .Values.hirevoiceNamespace | quote }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccountName | quote }}
            namespace: {{ .Values.externalSecretsNamespace | quote }}
