apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/kajapathy-k/AI_JOB_PORTAL_UPDATED.git
    targetRevision: eks-migration
    path: helm/external-secrets-resources
    helm:
      releaseName: external-secrets-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: hirevoice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
