apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hirevoice-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/kajapathy-k/AI_JOB_PORTAL_UPDATED.git
    targetRevision: personal-account-gitops
    path: helm/hirevoice
    helm:
      releaseName: hirevoice
  destination:
    server: https://kubernetes.default.svc
    namespace: hirevoice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
